# Generated by Django 5.0 on 2023-12-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
