# Generated by Django 4.2.4 on 2023-10-02 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_category_tag_post_categories_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2023, 10, 2, 16, 37, 7, 196714, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
