# Generated by Django 4.2.4 on 2023-10-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_category_name_alter_tag_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedpost',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='savedpost',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_user_post'),
        ),
    ]
