# Generated by Django 4.2.4 on 2023-10-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_savedpost_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
