# Generated by Django 4.2.6 on 2023-10-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_customuser_profile_picture_alter_customuser_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
    ]
