# Generated by Django 4.2.6 on 2023-10-27 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_customuser_address_alter_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 27, 20, 16, 30, 218760, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
