# Generated by Django 4.2.6 on 2023-10-31 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_post_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 10, 31, 21, 25, 29, 610107, tzinfo=datetime.timezone.utc), blank=True, null=True),
        ),
    ]
