# Generated by Django 4.2.6 on 2023-10-31 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_customuser_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 10, 31, 22, 50, 22, 305896, tzinfo=datetime.timezone.utc), blank=True, null=True),
        ),
    ]
