# Generated by Django 4.2.6 on 2023-10-31 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_post_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 10, 31, 23, 24, 0, 879350, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
