# Generated by Django 4.2.6 on 2023-11-02 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_post_date_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.post'),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='video',
            field=models.FileField(upload_to='post_videos/'),
        ),
    ]
