# Generated by Django 4.2.7 on 2023-11-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_comment_last_modified_remove_comment_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=320, unique=True),
        ),
    ]
