/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElementFooter: typeof import('./components/Element/Footer.vue')['default']
    ElementNavbar: typeof import('./components/Element/Navbar.vue')['default']
    ElementTheHeader: typeof import('./components/Element/TheHeader.vue')['default']
    ErrorAPIDown: typeof import('./components/Error/ErrorAPIDown.vue')['default']
    ErrorErrorAPIDown: typeof import('./components/Error/ErrorAPIDown.vue')['default']
    Footer: typeof import('./components/Element/Footer.vue')['default']
    FormFormLogin: typeof import('./components/form/FormLogin.vue')['default']
    FormFormRegister: typeof import('./components/form/FormRegister.vue')['default']
    FormLogin: typeof import('./components/form/FormLogin.vue')['default']
    FormRegister: typeof import('./components/form/FormRegister.vue')['default']
    MyUserPosts: typeof import('./components/MyUserPosts.vue')['default']
    Navbar: typeof import('./components/Element/Navbar.vue')['default']
    NavbarLoggedIn: typeof import('./components/navbar/NavbarLoggedIn.vue')['default']
    NavbarLoggedOut: typeof import('./components/navbar/NavbarLoggedOut.vue')['default']
    NavbarNavbarLoggedIn: typeof import('./components/navbar/NavbarLoggedIn.vue')['default']
    NavbarNavbarLoggedOut: typeof import('./components/navbar/NavbarLoggedOut.vue')['default']
    PostArticle: typeof import('./components/PostArticle.vue')['default']
    PostWindow: typeof import('./components/PostWindow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFeed: typeof import('./components/TheFeed.vue')['default']
    TheHeader: typeof import('./components/Element/TheHeader.vue')['default']
    TheWait: typeof import('./components/TheWait.vue')['default']
    UserSidebar: typeof import('./components/user/UserSidebar.vue')['default']
    UserUserSidebar: typeof import('./components/user/UserSidebar.vue')['default']
  }
}
