name: tests

on: push

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.10.0"

      - name: Install Dependencies
        run: yarn install
        working-directory: ./frontend

      - name: Run Tests
        run: yarn test
        working-directory: ./frontend

      - name: Build
        run: yarn build
        working-directory: ./frontend